#include <stdint.h>
#include "pipe.h"
#include "spinlock.h"
#include "process.h"

struct pipe_state{uint32_t used;uint32_t owner_pid;uint32_t readers;uint32_t writers;uint32_t head;uint32_t tail;uint32_t count;uint8_t data[LIONOS_PIPE_BUFFER];};
static struct pipe_state pipes[LIONOS_PIPE_MAX];
static struct spinlock pipe_lock;
static uint32_t pipe_channel(uint32_t id,uint32_t write_side){return 0x50495000u|(id<<1)|write_side;}
static int decode(uint32_t h,uint32_t*id,uint32_t*side){if(h<2u)return -1;uint32_t i=h>>1;if(i>=LIONOS_PIPE_MAX)return -1;if(id)*id=i;if(side)*side=h&1u;return 0;}
void pipe_init(void){spinlock_init(&pipe_lock);for(uint32_t i=0;i<LIONOS_PIPE_MAX;++i)pipes[i].used=0;}
int32_t pipe_create(uint32_t owner_pid,uint32_t*read_end,uint32_t*write_end){if(!owner_pid||!read_end||!write_end)return -1;uint32_t irq=spinlock_irqsave_acquire(&pipe_lock);for(uint32_t i=0;i<LIONOS_PIPE_MAX;++i)if(!pipes[i].used){struct pipe_state*p=&pipes[i];p->used=1;p->owner_pid=owner_pid;p->readers=1;p->writers=1;p->head=p->tail=p->count=0;*read_end=(i<<1);*write_end=(i<<1)|1u;spinlock_irqrestore_release(&pipe_lock,irq);return 0;}spinlock_irqrestore_release(&pipe_lock,irq);return -1;}
int32_t pipe_read(uint32_t handle,void*data,uint32_t capacity){uint32_t id,side;if(decode(handle,&id,&side)!=0||side||!data||!capacity)return -1;for(;;){uint32_t irq=spinlock_irqsave_acquire(&pipe_lock);struct pipe_state*p=&pipes[id];if(!p->used){spinlock_irqrestore_release(&pipe_lock,irq);return -1;}if(p->count){uint32_t n=p->count<capacity?p->count:capacity;uint8_t*d=data;for(uint32_t i=0;i<n;++i){d[i]=p->data[p->tail];p->tail=(p->tail+1u)%LIONOS_PIPE_BUFFER;}p->count-=n;spinlock_irqrestore_release(&pipe_lock,irq);process_wakeup((uintptr_t)pipe_channel(id,1));return (int32_t)n;}if(!p->writers){spinlock_irqrestore_release(&pipe_lock,irq);return 0;}int32_t b=process_sleep_on((uintptr_t)pipe_channel(id,0),&pipe_lock,irq);if(b==PROCESS_WAIT_BLOCKED)return b;if(b<0)return b;}}
int32_t pipe_write(uint32_t handle,const void*data,uint32_t length){uint32_t id,side;if(decode(handle,&id,&side)!=0||!side||!data||!length)return -1;const uint8_t*s=data;uint32_t done=0;for(;;){uint32_t irq=spinlock_irqsave_acquire(&pipe_lock);struct pipe_state*p=&pipes[id];if(!p->used||!p->readers){spinlock_irqrestore_release(&pipe_lock,irq);return done? (int32_t)done:-1;}uint32_t space=LIONOS_PIPE_BUFFER-p->count;if(space){uint32_t n=(length-done)<space?(length-done):space;for(uint32_t i=0;i<n;++i){p->data[p->head]=s[done+i];p->head=(p->head+1u)%LIONOS_PIPE_BUFFER;}p->count+=n;done+=n;spinlock_irqrestore_release(&pipe_lock,irq);process_wakeup((uintptr_t)pipe_channel(id,0));if(done==length)return (int32_t)done;continue;}int32_t b=process_sleep_on((uintptr_t)pipe_channel(id,1),&pipe_lock,irq);if(b==PROCESS_WAIT_BLOCKED)return done? (int32_t)done:PIPE_BLOCKED;if(b<0)return b;}}
int32_t pipe_close(uint32_t handle){uint32_t id,side;if(decode(handle,&id,&side)!=0)return -1;uint32_t irq=spinlock_irqsave_acquire(&pipe_lock);struct pipe_state*p=&pipes[id];if(!p->used){spinlock_irqrestore_release(&pipe_lock,irq);return -1;}if(side){if(p->writers)p->writers--;}else{if(p->readers)p->readers--;}if(!p->readers&&!p->writers)p->used=0;spinlock_irqrestore_release(&pipe_lock,irq);process_wakeup((uintptr_t)pipe_channel(id,0));process_wakeup((uintptr_t)pipe_channel(id,1));return 0;}
